version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.gpu
    tty: true
    volumes:
      - /mnt/c/repos/generative_deep_learning/data/:/app/data
      - /mnt/c/repos/generative_deep_learning/notebooks/:/app/notebooks
      - /mnt/c/repos/generative_deep_learning/scripts/:/app/scripts
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
        - "$JUPYTER_PORT:$JUPYTER_PORT"
        - "$TENSORBOARD_PORT:$TENSORBOARD_PORT"
    env_file:
     - ./.env
    entrypoint: jupyter lab --ip 0.0.0.0 --port=$JUPYTER_PORT --no-browser --allow-root
    